### ISSUE TITLE
FeatureRequest: Loading indicator

### ISSUE THREAD

**Issue by PeterHuewe** [grindhold/rainbow-lollipop#53] opened 2015-04-08 21:32 UTC
having a horribly slow internet connection it really sucks staring at a blank white page and figuring whether the browser does anything or is simply waiting to load the page.

**Comment by grindhold** [comment] 2015-04-08 21:43
duplicate of #31

**Comment by grindhold** [comment] 2015-04-15 10:43
closing as #31 has been closed

**Closed by grindhold** 2015-04-15 10:43 UTC
Labels: duplicate, enhancement
