### ISSUE TITLE
Cannot start on Arch.

### ISSUE THREAD

**Issue by Toqozz** [grindhold/rainbow-lollipop#63] opened 2015-04-20 07:12 UTC
I get this error when starting from terminal, (installed from aur).

```
┌─╼ [~]
└────╼ rainbow-lollipop

(rainbow-lollipop:22636): GLib-GObject-WARNING **: value "0" of type 'gint' is invalid or out of range for property 'window-scaling-factor' of type 'gint'

(rainbow-lollipop:22636): GLib-GObject-WARNING **: value "0" of type 'gint' is invalid or out of range for property 'dnd-drag-threshold' of type 'gint'

(rainbow-lollipop:22636): Gtk-WARNING **: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files

(rainbow-lollipop:22636): GLib-GObject-WARNING **: The property GtkSettings:gtk-menu-images is deprecated and shouldn't be used anymore. It will be removed in a future version.

** (rainbow-lollipop:22636): CRITICAL **: application_states.vala:102: TracklistState has not been intialized.

** (rainbow-lollipop:22636): CRITICAL **: application_states.vala:102: TracklistState has not been intialized.

(rainbow-lollipop:22636): Pango-CRITICAL **: pango_font_description_from_string: assertion 'str != NULL' failed

(rainbow-lollipop:22636): Pango-CRITICAL **: pango_font_description_equal: assertion 'desc1 != NULL' failed

(rainbow-lollipop:22636): Pango-CRITICAL **: pango_font_description_from_string: assertion 'str != NULL' failed

(rainbow-lollipop:22636): Pango-CRITICAL **: pango_font_description_equal: assertion 'desc1 != NULL' failed
/usr/share/rainbow-lollipop/restore_session.png

(rainbow-lollipop:22636): Pango-CRITICAL **: pango_font_description_from_string: assertion 'str != NULL' failed

(rainbow-lollipop:22636): Pango-CRITICAL **: pango_font_description_equal: assertion 'desc1 != NULL' failed

(rainbow-lollipop:22636): Clutter-CRITICAL **: clutter_actor_add_child: assertion 'child->priv->parent == NULL' failed

(rainbow-lollipop:22636): Gtk-CRITICAL **: gtk_widget_get_preferred_height: assertion 'GTK_IS_WIDGET (widget)' failed

(rainbow-lollipop:22636): Gtk-CRITICAL **: gtk_widget_get_preferred_width: assertion 'GTK_IS_WIDGET (widget)' failed

(rainbow-lollipop:22636): Gtk-CRITICAL **: gtk_widget_get_preferred_height: assertion 'GTK_IS_WIDGET (widget)' failed

(rainbow-lollipop:22636): Gtk-CRITICAL **: gtk_widget_get_preferred_width: assertion 'GTK_IS_WIDGET (widget)' failed

(rainbow-lollipop:22636): Pango-CRITICAL **: pango_font_description_from_string: assertion 'str != NULL' failed

(rainbow-lollipop:22636): Pango-CRITICAL **: pango_context_set_font_description: assertion 'desc != NULL' failed

(rainbow-lollipop:22636): Pango-CRITICAL **: pango_font_description_from_string: assertion 'str != NULL' failed

(rainbow-lollipop:22636): Pango-CRITICAL **: pango_context_set_font_description: assertion 'desc != NULL' failed

(rainbow-lollipop:22636): Pango-CRITICAL **: pango_font_description_from_string: assertion 'str != NULL' failed

(rainbow-lollipop:22636): Pango-CRITICAL **: pango_context_set_font_description: assertion 'desc != NULL' failed

(rainbow-lollipop:22636): Pango-CRITICAL **: pango_font_description_from_string: assertion 'str != NULL' failed

(rainbow-lollipop:22636): Pango-CRITICAL **: pango_context_set_font_description: assertion 'desc != NULL' failed

(rainbow-lollipop:22636): Pango-CRITICAL **: pango_font_description_from_string: assertion 'str != NULL' failed

(rainbow-lollipop:22636): Pango-CRITICAL **: pango_context_set_font_description: assertion 'desc != NULL' failed

(rainbow-lollipop:22636): Pango-CRITICAL **: pango_font_description_from_string: assertion 'str != NULL' failed

(rainbow-lollipop:22636): Pango-CRITICAL **: pango_context_set_font_description: assertion 'desc != NULL' failed

(rainbow-lollipop:22636): Pango-CRITICAL **: pango_font_description_from_string: assertion 'str != NULL' failed

(rainbow-lollipop:22636): Pango-CRITICAL **: pango_context_set_font_description: assertion 'desc != NULL' failed

(rainbow-lollipop:22636): Pango-CRITICAL **: pango_font_description_from_string: assertion 'str != NULL' failed

(rainbow-lollipop:22636): Pango-CRITICAL **: pango_context_set_font_description: assertion 'desc != NULL' failed

(rainbow-lollipop:22636): Gdk-ERROR **: The program 'rainbow-lollipop' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadMatch (invalid parameter attributes)'.
  (Details: serial 299 error_code 8 request_code 154 (GLX) minor_code 31)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
Trace/breakpoint trap (core dumped)
```

**Comment by grindhold** [comment] 2015-04-20 07:18
pretty strange. it was really right after startup? the ui didn't even show up?

Also this should not happen: 
```
** (rainbow-lollipop:22636): CRITICAL **: application_states.vala:102: TracklistState has not been intialized.

** (rainbow-lollipop:22636): CRITICAL **: application_states.vala:102: TracklistState has not been intialized.
```

**Comment by Toqozz** [comment] 2015-04-20 10:21
No gui on start no.  I tried with a different gtk theme however did not try checking out fonts.  It's possible, It's a relatively new install and I've barely installed any fonts (microsoft fonts & terminus).  I do of course have the Arch base fonts installed.  Have not had a problem with other programs, steam at first, yet it doesn't complain anymore.

**Comment by lukasepple** [comment] 2015-04-25 12:35
Fonts I have installed:
```
extra/bdf-unifont 7.0.06-2 [Installiert]
extra/cantarell-fonts 0.0.16-2 [Installiert]
extra/fluidsynth 1.1.6-4 [Installiert]
extra/fontconfig 2.11.1-1 [Installiert]
extra/fontsproto 2.1.3-1 [Installiert]
extra/freetype2 2.5.5-1 [Installiert]
extra/gnome-font-viewer 3.16.0-1 (gnome) [Installiert]
extra/gsfonts 20150122-1 [Installiert]
extra/libfontenc 1.1.2-1 [Installiert]
extra/libotf 0.9.13-2 [Installiert]
extra/libxfont 1.5.1-1 [Installiert]
extra/libxft 2.3.2-1 [Installiert]
extra/sdl_ttf 2.0.11-3 [Installiert]
extra/t1lib 5.1.2-5 [Installiert]
extra/texlive-fontsextra 2014.36711-1 (texlive-most) [Installiert]
extra/texlive-genericextra 2014.36662-1 (texlive-most) [Installiert]
extra/texmacs 1.99.2-1 [Installiert]
extra/ttf-dejavu 2.34-2 [Installiert]
extra/ttf-freefont 20120503-4 [Installiert]
extra/ttf-linux-libertine 5.3.0-3 [Installiert]
extra/xorg-bdftopcf 1.0.5-1 (xorg xorg-apps) [Installiert]
extra/xorg-font-util 1.3.1-1 (xorg-fonts xorg) [Installiert]
extra/xorg-font-utils 7.6-4 [Installiert]
extra/xorg-fonts-alias 1.0.3-1 [Installiert]
extra/xorg-fonts-encodings 1.0.4-4 (xorg-fonts xorg) [Installiert]
extra/xorg-fonts-misc 1.0.3-3 [Installiert]
extra/xorg-mkfontdir 1.0.7-2 (xorg xorg-apps) [Installiert]
extra/xorg-mkfontscale 1.1.2-1 (xorg-apps xorg) [Installiert]
extra/xorg-xfontsel 1.0.5-1 [Installiert]
community/terminus-font 4.39-1 [Installiert]
community/ttf-anonymous-pro 1.003-2 [Installiert]
community/ttf-inconsolata 20090215-5 [Installiert]
community/ttf-ubuntu-font-family 0.80-5 [Installiert]
multilib/lib32-fontconfig 2.11.1-1 [Installiert]
multilib/lib32-freetype2 2.5.5-1 [Installiert]
```

I use Adwaita as theme.

**Comment by tobyp** [comment] 2015-05-07 22:04
@lukasepple @Toqozz can you confirm whether you're using nvidia binary blobs, please.

I reduced the code to a minimal example [0] that maintains the error, and found that the problem seems to lie in clutter/cogl. Knowing this, I found a blog post [1] that suggests the cause to be changes to the glx backend of gtk+ 3.16. Technical details/patches see [2]

If you can, please test with a non-nvidia driver and see if the problem persists there. It seems there's no fix short of building your own patched version of cogl at the moment.

[0]
    /* valac --pkg gtk+-3.0 --pkg clutter-gtk-1.0 --pkg clutter-1.0 gctest.vala */

    using Gtk;
    using GtkClutter;
    using Clutter;

    public static int main(string[] args) {
        if (GtkClutter.init(ref args) != Clutter.InitError.SUCCESS){
            stdout.printf("Could not initialize GtkClutter");
        }
        
        new GtkClutter.Window().show_all();
        Gtk.main();

        return 0;
    }

[1] http://blog.sukimashita.com/2015/04/13/gnome-3-16-and-nvidia-binary-driver-crash-with-totem-gnome-maps-cheese-and-others/

[2] https://bugzilla.gnome.org/show_bug.cgi?id=747489

**Comment by lukasepple** [comment] 2015-05-08 09:40
My Intel HD is used for rl. I could try to run it on my NVIDIA card and see wether it crashes there.

**Comment by grindhold** [comment] 2015-05-08 09:40
awesome, seeing something going on here :)

**Comment by Toqozz** [comment] 2015-05-08 09:56
Im using the standard nvidia package from arch repositories.  As I rely on this computer for work right now, I don't really want to mess around with the drivers, sorry.

**Comment by tobyp** [comment] 2015-05-08 13:59
rainbow-lollipop works on my laptop, using i915 instead of nvidia.

**Comment by jjryan** [comment] 2015-06-16 12:20
This might be fixed now in arch with the new version of clutter. https://bugzilla.gnome.org/show_bug.cgi?id=747489 has been resolved.

**Comment by grindhold** [comment] 2015-06-16 12:26
@jjryan thx for the input, can someone on arch confirm this?

**Comment by lukasepple** [comment] 2015-06-16 12:37
rainbow-lollipop works fine for me.

**Comment by grindhold** [comment] 2015-06-16 12:40
@lukasepple when you run it on your nvidia-box?

**Comment by jjryan** [comment] 2015-06-16 20:55
I can confirm it works on Arch. I forget what my video card is though, either AMD or Nvidia.

**Comment by grindhold** [comment] 2015-06-17 00:32
@jjryan this is actually important. the problem only occurs when you have an nvidia gpu together with nvidia's proprietary drivers

**Comment by etbh** [comment] 2015-06-18 08:18
Still doesn't work for me on Arch with nvidia proprietary drivers.
The patches have been pushed 8 days ago and will take effect with clutter 1.22.3 and clutter-gtk 1.6.1.  
As there's no devel package for clutter-gtk on Arch, recompiling rainbow-lollipop with development version won't be trivial.  
Interesting note : I have the exact same issue with emerillon, an OpenStreeMap viewer that uses clutter too.

**Comment by grindhold** [comment] 2015-06-18 08:29
@etbh thanks for the input. So we still play the waiting game.

**Comment by Toqozz** [comment] 2015-06-20 04:00
Well, I no longer get the same error.  Now I get: 
┌─╼ [~]
└────╼ rainbow-lollipop 
rainbow-lollipop: error while loading shared libraries: libzmq.so.4: cannot open shared object file: No such file or directory

I have the latest version of ZeroMQ installed, did some looking the other day but could only find threads related to libzmq.so.3, which were seemingly fixed by installing ZeroMQ.

**Comment by Toqozz** [comment] 2015-06-20 04:11
oop, updated the system again (since about 2 days ago), same error as above.

I then reinstalled from the aur.  Now I receive something similar to the original error: 

┌─╼ [~]
└────╼ rainbow-lollipop 

(rainbow-lollipop:28676): Gdk-ERROR **: The program 'rainbow-lollipop' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 177 error_code 2 request_code 154 (GLX) minor_code 24)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
Trace/breakpoint trap (core dumped)

**Comment by tobyp** [comment] 2015-06-20 17:31
The error persists for me as well. I tried the little vala script from last time again and it produced the same error, which leads me to believe the cogl patches haven't reached us yet.
I guess, as @etbh  and @grindhold say, we'll continue the waiting game.

**Comment by etbh** [comment] 2015-06-30 12:09
extra/clutter and extra/clutter-gtk have just been updated. Now it works.

**Comment by grindhold** [comment] 2015-06-30 12:26
@etbh   \o/  awesome news!  I'll wait for some more confirmations @tobyp  @Toqozz  *hint*  and then close the issue. Thanks for keeping track of clutter's progress on this matter.

**Comment by Toqozz** [comment] 2015-07-01 13:49
Fixed :)

**Comment by grindhold** [comment] 2015-07-01 14:11
@Toqozz  thanks

**Closed by grindhold** 2015-07-01 14:11 UTC
Labels: bug, help wanted
